import type { Metadata } from "next";
import Navbar from "../components/navbar";
import Footer from "../components/footer";
import Alert from "../components/alert";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="fa">
      <body>
        <Navbar/>
        <Alert />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
